### ISSUE TITLE
Debugging time is too long. Please upgrade to a more user-friendly version and add the database required by alphafold.

### ISSUE THREAD

**Issue by Defphoenix** [piercelab/tcrmodel2#1]
This software does not use the GPU. We encountered a lot of problems with CUDA 11.6 and 2080ti even after fixing multiple absolute path issues and some bugs. Have you tested this software in a non-development environment? The bugs I encountered include:

Absolute path issues
Failure to check the existence of files or variables
ml_collections package installation issues
Running numpy_core with GPU issues
Errors caused by missing list items, etc.

I hope the development team can provide more detailed documentation. My worst bug is that the test commands in the documentation use absolute paths instead of command-line arguments, such as:
**--ori_db=/path/to/folder/with/pdb_mmcif/
It's hard-coded in the file like this:**
flags.DEFINE_string('data_dir', "/scratch/Pierce/alphafold_v2.3_db/",
'Path to directory of supporting data.')
This makes it impossible for non-professionals in our lab to solve the problem.

After dealing with many bugs with gratitude, we have had a very bad experience. Please provide some simple support for this project, developers.

**Comment by rui-yin** [comment]
Dear user, 

Thank you for bringing the issues to our attention. We have made updates to both the code and documentation to address some concerns you raised. We want to clarify that the placeholder path "/path/to/folder/with/pdb_mmcif/" in the documentation is intended to be replaced by the actual path to the directory containing the pdb_mmcif files, as indicated in step #2 of the "Download database" guide (refer to: https://github.com/piercelab/tcrmodel2#download-database).  

In the meantime, we highly recommend utilizing our webserver at https://tcrmodel.ibbr.umd.edu/ for generating predictions. The webserver offers a user-friendly interface and allows you to generate predictions without the need for local installations or encountering the issues you experienced.

Best regards, 
Rui Yin
