### ISSUE TITLE
Latent representation of multimere

### ISSUE THREAD

**Issue by cirdeCyL** [piercelab/tcrmodel2#10]
Hi,

I am working with your great pipeline and it works for me.
I am just wondering if there is a possibility to get the latent representation of the multimeres next to the pdbs.
I change the parameter return_representations from file alphafold/model/module_multimere.py line 310 + line 424 from False -> True.

In file run_alphafold_tcrmodel2.3.py I added lines to save the representation.
My question is:
"Is this the representation of the whole multimere or just from one monomere which is part of the multimere?"
The representation is split up in 'single', 'paired', 'structure_module', 'msa' and 'msa_first_row' is there any way documentation what they are in the context of multimeres?

Thank you for the great work and I can not wait to see your response.

CHeers

**Comment by rui-yin** [comment]
Hi @cirdeCyL,

Thank you for your kind words! Your question seems to pertain more directly to the original AlphaFold-Multimer code (alphafold/model/module_multimere.py). I would strongly recommend checking with the AlphaFold-Multimer team for a definitive answer, but I will try my best to share my thoughts.

Regarding your initial inquiry, based on my understanding, the representation you saved is for the entire Multimer. For your subsequent question on the representations within the Multimer context: the elements in the representation dictionary align with those in the Monomer. This is consistent with the fact that the Multimer largely preserves its foundational architecture as indicated in the [Multimer preprint](https://www.biorxiv.org/content/10.1101/2021.10.04.463034v2.full). For deeper insights, Jumper et al., 2021 is a valuable reference. In particular, Figure 1 from Jumper et al., 2021 provides a visualization showing each dictionary element in the context of the architecture: [link to Figure 1](https://www.nature.com/articles/s41586-021-03819-2/figures/1). 

Hope this provides some clarity!

Best,
Rui

**Comment by rui-yin** [comment]
Since there haven't been any further questions and a response has been provided, I'm going to close this issue. If you have any more questions or if there's anything else you need clarification on, please feel free to reopen this issue or start a new one. Thanks for reaching out!
