### ISSUE TITLE
Update of installation instructions

### ISSUE THREAD

**Issue by andreas-wilm** [piercelab/tcrmodel2#11]
Hi there

Many thanks for making TCRModel2 available! 

Would it be possible to update the installation routines or provide a Docker/Singularity image? I tried multiple times hard to install TCRModel2 without success. Yes, I could use the webserver, but that's only good for very few predictions.

Thanks again,
Andreas

**Comment by rui-yin** [comment]
Hi Andreas, 

Thanks for reaching out! We've added a Singularity container for TCRModel2 to simplify installation and usage. You can find it in our latest commit at [fe5fe3f](https://github.com/piercelab/tcrmodel2/commit/fe5fe3f8c8fd5f4804883c027ae461c37aba3f93). Detailed instructions are in the README.

Hope this enhances your experience with TCRModel2. Please feel free to reach out if you have further questions or suggestions.

Best,
Rui

**Comment by andreas-wilm** [comment]
Awesome work! Works like a charm!  Thank you so very much.
