### ISSUE TITLE
Combining singularity container with nohup: Kalign fails

### ISSUE THREAD

**Issue by andreas-wilm** [piercelab/tcrmodel2#15]
Hi Rui and team,

I came across a rather weird phenomenon and am not whether this can be attributed to the TCRModel2 Singularity image, Singularity itself or its combination with nohup.

When run with nohup the images fails at the Kalign step: it first seems to hang and then you get `SequenceNotInTemplateError()`, `RuntimeError('Kalign failed')` (empty stdout and stderr) and `QueryToTemplateAlignError()` in `/opt/tcrmodel2/alphafold/data/templates.py`

This happens when Singularity is run with nohup, or, as in my case, it even propgates when using a wrapper script with nohup. I don't understand how this makes sense. The solution is to just not call Singularity (or a wrapper) with nohup.  Feel free to close this issue immediately. It was just meant as a reference in case someone comes across this as well.

Andreas

PS: Singularity version 3.7.4 and 2.6.1

**Comment by rui-yin** [comment]
Hi Andreas,

Noted! Thank you very much for letting us know your observations and solutions! We really appreciate it. :D

Best,
Rui
