### ISSUE TITLE
Singularity link broken?

### ISSUE THREAD

**Issue by nickrrose** [piercelab/tcrmodel2#17]
Hi! I can't seem to follow the link for the pre built singularity link, is it not available yet or is there an issue on my end?

**Comment by rui-yin** [comment]
Hi Nick,

Thank you for bringing this to our attention! You're correct—the link to the .sif file appeared to be broken. I've now updated the download link in the following commit: [dbe68c2](https://github.com/piercelab/tcrmodel2/commit/dbe68c2e8f1a26ad2b40aefccc957b3f78677536).

Here's the corrected link to the .sif file for your convenience:
https://piercelab.ibbr.umd.edu/alphafold_tcrmodel_test_cuda112_tfgpu.sif

Please feel free to reach out again if you have any more questions.

Cheers,
Rui
