### ISSUE TITLE
Model output - JSON data with inconsistent types

### ISSUE THREAD

**Issue by kamurani** [piercelab/tcrmodel2#19]
Hello, 

Not sure if this is an issue with the webserver only, but looking at the `statistics.json` file after running a model, it appears that the model confidence metrics are encoded as strings, except the `cdr3a_plddt` and `cdr3b_plddt` scores. 

Is there any reason for this?

Example 
```json
{
    "ranked_0": {
        "model_confidence": "0.8622094003450296",
        "plddt": "91.89734278967342",
        "ptm": "0.8834439953622326",
        "iptm": "0.85690075",
        "tcr-pmhc_iptm": "0.8189073889850327",
        "cdr3a_plddt": 71.72926654290715,
        "cdr3b_plddt": 78.55616743449073
    },
```

**Comment by rui-yin** [comment]
Hi Kâmuran,

Thank you for bringing this to our attention. The reason for the inconsistent data types issue is that the scores are being read or calculated differently. We will adjust the code to make the output uniform in the next few days. 

Best,
Rui

**Comment by shayanask** [comment]
Hi Kâmuran,

The code has been adjusted. The output should be of the same type now.
