### ISSUE TITLE
Unclear modelling statistics output on webpage view

### ISSUE THREAD

**Issue by kamurani** [piercelab/tcrmodel2#20]
When viewing the modelling output on some jobs, there appears to be a ⚠ symbol next to some model confidence scores.  

However, it is not clear on this page (or the additional information section) what this symbol means.  

![image](https://github.com/piercelab/tcrmodel2/assets/73625486/8884476e-2c9b-4be7-8f5e-5bbc5e40ab3e)

A reference and explanation to this on the GUI somewhere would be useful for interpretability.

**Comment by bpierce12** [comment]
Hi Kâmuran,

Thank you for checking on this. This is described on the TCRmodel2 Help
page, in the Results section under "Docking and Incident Angles":
"If the output model presents an unusual TCR binding mode, a warning icon
will appear on the right side of the model confidence together with a
message informing the unusual binding mode to the user."
Next to that section, there is an image of results with those warning
symbols. Additionally, when users mouse-over that symbol in their own
results, a brief explanation message pops up (the "message" that the Help
page is referring to). Let us know if you have any more questions or issues
with the server.

Best
Brian

**Comment by bpierce12** [comment]
Closing as this is already described on Help page and via mouse-over. Can potentially make this information more prominent in future TCRmodel2 updates.
