### ISSUE TITLE
Feature Request and Usage Issue

### ISSUE THREAD

**Issue by KiAkize** [piercelab/tcrmodel2#8]
Thank you for open-sourcing such excellent work! I would like to make some feature requests and report some issues encountered during actual use.

1. Feature request: I noticed that on the web version, it is possible to select the TCR α or b sequence from genes and to select the MHC type as input. Can this feature be updated to the local version? Currently, the local version can only use the complete amino acid sequence as input, but most databases such as VDJdb only provide VJ germlines, making it inconvenient to use TCRModel2 for prediction.

2. Usage issue: As with the aforementioned VDJdb database, it is often only possible to obtain information on a single TCR-b chain or TCR-a chain. Is there a way to predict the binding structure of TCR-b-pMHC when only the TCR-b chain is known? 

I look forward to your reply. Thank you!

**Comment by rui-yin** [comment]
Hi @KiAkize,

Thank you for reaching out! 

1. In regards to updating the local version to accept inputs similar to the web version: Unfortunately integrating this feature directly into TCRModel2 repo may not be feasible in the near future. As an alternative, we'd suggest considering using a separate program, for instance, stitchr (link: https://github.com/JamieHeather/stitchr), which may be helpful in assembling TCR sequence from V/J/CDR3 information. 

2. Regarding the prediction of TCR-pMHC with only the TCR-b chain: We currently don't have a reliable solution within TCRmodel2 without further benchmarking. One potential workaround might be to use a randomly selected alpha chain. Alternatively, you can experiment with AF2.3 to use just the beta chain and pMHC as input. 

Hopefully these suggestions can offer some help! Please don’t hesitate to reach out to us if you have further questions.

Best,
Rui

**Comment by KiAkize** [comment]
Sorry for the late response.
Thanks a lot for your advice :)

**Comment by rui-yin** [comment]
No problem! I hope the suggestions were helpful.
