### ISSUE TITLE
Use case question: ranking of pMHC/TCR compatibility

### ISSUE THREAD

**Issue by andreas-wilm** [piercelab/tcrmodel2#9]
Thank you for creating and sharing TcrModel2!

I was wondering if I could use TcrModel2 to rank a list of peptides (fixed MHC) against a TCR, or likewise, could I rank a list of TCRs against pMHCs based on their structural compatibility? For this, TCRDock has the concept of a binding score, which is  computed by taking the AlphaFold PAE for the TCR:pMHC interface and subtracting TCR-intrinsic and pMHC-intrinsic factors (see e.g. Figure 3 in the [TCRDock paper](https://elifesciences.org/articles/82813)). Can something similar by achieved by using TcrModel2'sTCR-pMHC ipTM or is this score on its own already a good proxy?

Many thanks, Andreas

**Comment by bpierce12** [comment]
Hi Andreas, thanks for checking. We indeed have thought about it, and
performed some preliminary tests of that, but haven't had the opportunity
to perform full-scale testing and development for that scenario. Our
preliminary tests indicated that interface pLDDT score is possibly more
predictive of true interactions, but we have much more to do before coming
to any clear conclusions. If we do end up moving ahead with that, we can
let you and others know via web server and/or Github update (and a
preprint/writeup, if warranted).

Best,
Brian

**Comment by andreas-wilm** [comment]
Excellent. Thanks!
